### ISSUE TITLE
Why does the video content not match the text?

### ISSUE THREAD

**Issue by zhengshi119** [afford-motion/afford-motion#11]
https://github.com/user-attachments/assets/73a3d8a3-5617-416c-8928-70cc97882216

I use the model and dataset you have provided. And I use the flowing code to run: 
bash scripts/novel_contact/test.sh /root/workspace_zs/model/model_afford/CDM-Perceiver-ALL/ 2024
bash scripts/novel_contact_motion/test.sh /root/workspace_zs/model/model_afford/CMDM-Enc-ALL/ /root/workspace_zs/model/model_afford/CDM-Perceiver-ALL/eval/test-0912-114901/ 2024

**Comment by Silverster98** [comment]
Hi,

Sorry for this late reply. I’m unsure if there were issues with your reproduction process, but I want to emphasize two points.

First, for clearer visualization, you can use the skeleton instead of the SMPL mesh, as SMPL parameters are fitted from the skeleton and may not always align well. Second, the focused task, which was introduced recently, is highly challenging due to data scarcity and its inherent complexity. It's unrealistic to expect the model to handle all cases and produce plausible results in every instance. Besides, you test the model on our Novel Evaluation Set, which is much more challenging for the model to generate plausible motions. **We acknowledge that the results in our paper are cherry-picked.**

Our work represents an early attempt at addressing this task, and further efforts are needed to improve generation quality in this task.
